### ISSUE TITLE
default setting needed

### ISSUE THREAD

**Issue by dsmeshram** [awslabs/aws-js-s3-explorer#57]
when we start the tool the bucket dialog appearing. supposed I don't want to show that dialog and get the data from s3. there have any default setting for this soi can just set the default and it'll get the data for me

**Comment by john-aws** [comment]
I'm assuming that you are referring to the [v2-alpha](https://github.com/awslabs/aws-js-s3-explorer/tree/v2-alpha) branch.

You could certainly modify the source code for your own local use. For example, you could pre-populate the bucket name in the settings object and then short-circuit the modal settings dialog. However, one thing that the settings dialog does is ask you for AWS credentials. How would you propose to get credentials into the page? Hard-coding them would not typically be a good idea.

**Comment by dsmeshram** [comment]
thanks for your replay. very first my requirement is I don't want to give anyone upload/add options only end users can view and download the data from the s3. so whenver my this app on s3 end user can explore the bucket. I don't want to give anyone to set settings.

**Comment by john-aws** [comment]
If you want simple view/download function for an S3 bucket with publicly-accessible objects (so users do not have to authenticate) then that is what v1 of this project does (see the [master](https://github.com/awslabs/aws-js-s3-explorer/) branch).

If you want users to authenticate so that they can access non-public objects then you should use v2 of this project (see the [v2-alpha](https://github.com/awslabs/aws-js-s3-explorer/tree/v2-alpha) branch). If you want to suppress some of the features of v2, for example upload and delete, then you one option is to fork this project and make any modifications that you need.

**Comment by john-aws** [comment]
Hi @dsmeshram, I hope you were able to modify the project to get the features you wanted.

Please re-open this issue if there's anything we can help with.
